#!/bin/sh

##############################################################################
#                                                                            #
#  This file is part of factoradic_c_utils.                                  #
#                                                                            #
#  factoradic_c_utils is free software: you can redistribute it and/or       #
#  modify it under the terms of the GNU General Public License as published  #
#  by the Free Software Foundation, either version 3 of the License,         #
#  or (at your option) any later version.                                    #
#                                                                            #
#  factoradic_c_utils is distributed in the hope that it will be useful,     #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of            #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General  #
#  Public License for more details.                                          #
#                                                                            #
#  You should have received a copy of the GNU General Public License along   #
#  with factoradic_c_utils. If not, see <https://www.gnu.org/licenses/>.     #
#                                                                            #
##############################################################################

. "${srcdir}/tests/test_helper.sh"

set_test_program dec2fact

assert_output   0 0
assert_output 1:0 1

assert_output   3:4:1:0:1:0 463
assert_output   5:4:3:2:1:0 719
assert_output 1:0:0:0:0:0:0 720

end_of_tests 


# Local Variables:
# mode: sh
# sh-basic-offset: 4
# sh-shell: sh
# coding: unix
# End:
